### PR TITLE
Forcing x axis limits to include 0 when no explicit range is available.

### LINKED ISSUE #120: Include TIME = 0 in finegrid plot
Finegride Plot do not include TIME =0. Need to include them.

Statement captured in Ticket #87 :

The only exception is with finegrid. We keep only positive TIME>0._

### PR DESCRIPTION
**Pull request by tynesjo**
To resolve #120 
Have been unable to detect missing 0 label and break with new code,
but do not have reproducible example of error..

Below is finegrid plot with 0 label on x axis:
fine

### CODE REVIEW

File: R/plot-base.R [hunk 1]
```diff
@@ -39,9 +37,14 @@ plot_pmx.pmx_gpar <- function(gpar, p) {
       p <- p %+% scale_y_continuous(limits = ranges[["y"]])
     }
     if (!is.null(ranges$x) && !discrete) {
+      print(ranges[["x"]])
```
Comment (mattfidler) [inline R/plot-base.R:40]: Need to remove print

**Review by mattfidler — CHANGES_REQUESTED** [review]
